[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "substratumx"
version = "0.1.6"
requires-python = ">=3.8"
description = "An NdArray library supporting numerical computation and spatial analysis."
readme = "README.md"

[tool.maturin]
features = ["pyo3/extension-module"]
include = ["substratum.pyi"]
module-name = "substratum"
python-source = "python"
